shambomon/lib/shambomon_web/router.ex
defmodule ShambomonWeb.Router do
  use ShambomonWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # Taken from Nat's lecture notes
  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Shambomon.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShambomonWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/game", PageController, :name
    get "/game/:game", PageController, :game
    get "/game/:game/characters", PageController, :characters

    resources "/users", UserController

    # Taken from Nat's lecture notes
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", ShambomonWeb do
     pipe_through :api
     resources "/matches", MatchController, except: [:new, :edit]
  end
end

shambomon/lib/shambomon_web/templates/page/characters.html.eex
<%= render ShambomonWeb.ComponentView, "header.html", assigns %>
<%= if @current_user do %>
<div class="centered" id="characters">
  <script>
    window.gameName = "<%= @game %>";
  </script>
  <h1 class="ribbon">
    <div class="ribbon-content">SELECT CHARACTER</div>
  </h1>
  <table>
    <tbody>
      <tr>
        <%= for character <- @characters1 do %>
          <th><%= character.name %></th>
        <% end %>
      </tr>
      <tr>
        <%= for character <- @characters1 do %>
          <td>
            <!-- Image credits to Jedflah on DeviantArt -->
            <!-- <%= character.credits %> -->
            <img src="<%= character.source %>" alt="<%= character.name %>"
              class="character-icon"/>
          </td>
        <% end %>
      </tr>
      <tr>
        <%= for character <- @characters2 do %>
          <th><%= character.name %></th>
        <% end %>
      </tr>
      <tr>
        <%= for character <- @characters2 do %>
          <td>
            <!-- Image credits to Jedflah on DeviantArt -->
            <!-- <%= character.credits %> -->
            <img src="<%= character.source %>" alt="<%= character.name %>"
              class="character-icon"/>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <input type="hidden" id="user-id" value=<%= @current_user.id %>>
  <input type="hidden" id="username" value=<%= @current_user.username %>>
</div>

<% else %>
<%= render ShambomonWeb.ComponentView, "no_session.html", assigns %>

<% end %>

shambomon/lib/shambomon_web/templates/page/game.html.eex
<%= render ShambomonWeb.ComponentView, "functions.html", assigns %>

<%= if @current_user do %>
<%= render ShambomonWeb.ComponentView, "help.html", assigns %>
<div class="row">
  <div class="col-md-9">
    <h1 class="shambomon-header">SHAMBOMON</h1>
  </div>
  <div class="col-md-3">
    <div class="top-right">
      <%= @current_user.username %>
      <p class="divider"> | </p>
      <a href="javascript:void(0);"
        onclick="toggle_three('battlefield', 'help-pg-1', 'help-pg-2')">
        HELP
      </a>
      <!-- TODO: implement mid-game quitting if time permits
      <p class="divider"> | </p>
      <%= link "QUIT", to: "/session", method: :delete %> -->
    </div>
  </div>
</div>
<div class="row" id="game">
  <div class="centered">
    <script>
      window.gameName = "<%= @game %>";
    </script>
    <p>React app not loaded...</p>
    <input type="hidden" id="user-id" value=<%= @current_user.id %>>
    <input type="hidden" id="username" value=<%= @current_user.username %>>
  </div>
</div>

<% else %>
<%= render ShambomonWeb.ComponentView, "header.html", assigns %>
<%= render ShambomonWeb.ComponentView, "no_session.html", assigns %>

<% end %>

shambomon/lib/shambomon_web/templates/page/index.html.eex
<%= if @current_user do %>
<%= render ShambomonWeb.PageView, "name.html", assigns %>

<% else %>
<%= render ShambomonWeb.ComponentView, "functions.html", assigns %>
<%= render ShambomonWeb.ComponentView, "index_background.html", assigns %>
<%= render ShambomonWeb.ComponentView, "header.html", assigns %>

<!-- MAIN PAGE -->
<div class="centered" id="main">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="right-side">
        <%= link "REGISTER", to: user_path(@conn, :new) %>
        <p class="divider"> | </p>
        <a href="javascript:void(0);"
          onclick="toggle_three('main', 'pg-1', 'pg-2')">
          HOW TO PLAY
        </a>
        <p class="divider"> | </p>
        <%= link "LEADERBOARD", to: user_path(@conn, :index) %>
      </div>
    </div>
  </div>
  <!-- LOG-IN FORM -->
  <%= form_tag("/session", method: :post) do %>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="form-group">
          USERNAME:
          <input class="form-control" type="username" name="username">
        </div>
        <div class="form-group">
          PASSWORD:
          <input class="form-control" type="password" name="password">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="form-group">
          <button class="btn btn-primary">LOG IN</button>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id="index-help">
  <%= render ShambomonWeb.ComponentView, "instructions.html", assigns %>
</div>
<% end %>

shambomon/lib/shambomon_web/templates/page/name.html.eex
<%= render ShambomonWeb.ComponentView, "functions.html", assigns %>
<%= render ShambomonWeb.ComponentView, "background.html", assigns %>
<%= render ShambomonWeb.ComponentView, "header.html", assigns %>

<%= if @current_user do %>
<!-- MAIN PAGE -->
<div class="centered" id="main">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="right-side">
        <a href="javascript:void(0);"
          onclick="toggle_three('main', 'pg-1', 'pg-2')">
          HOW TO PLAY
        </a>
        <p class="divider"> | </p>
        <%= link "LEADERBOARD", to: user_path(@conn, :index) %>
      </div>
    </div>
  </div>
  <!-- GAME-NAME FORM -->
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <p>ENTER A GAME NAME:</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="GAME NAME" id="g-name">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="form-group">
        <button class="btn btn-primary" id="start-btn">BEGIN BATTLE</button>
      </div>
    </div>
  </div>
</div>
<%= render ShambomonWeb.ComponentView, "instructions.html", assigns %>

<% else %>
<%= render ShambomonWeb.ComponentView, "no_session.html", assigns %>

<% end %>